const I18N = {
  id: {
    nav_tools: 'ALAT', nav_convert: 'KONVERSI', nav_finance: 'KEUANGAN',
    nav_standard: 'Standard', nav_scientific: 'Scientific', nav_programmer: 'Programmer',
    nav_currency: 'Mata Uang', nav_unit: 'Konversi Unit', nav_finance_calc: 'Finansial', nav_zakat: 'Kalkulator Zakat',
    settings_lang: 'Bahasa', settings_theme: 'Tema', settings_history: 'Riwayat',
    cur_title: 'Konversi Mata Uang', cur_amount: 'Jumlah', cur_from: 'Dari', cur_to: 'Ke',
    unit_title: 'Konversi Satuan', unit_sub: '10 kategori konversi lengkap', unit_value: 'Nilai', unit_from: 'Dari', unit_to: 'Ke',
    fin_title: 'Kalkulator Finansial', fin_sub: 'Investasi, Kredit, Pajak & Kesehatan',
    fin_loan: 'KPR/Kredit', fin_compound: 'Bunga Majemuk', fin_discount: 'Diskon',
    loan_amount: 'Jumlah Pinjaman (Rp)', loan_rate: 'Suku Bunga / Tahun (%)', loan_term: 'Tenor (Bulan)',
    ci_principal: 'Modal Awal (Rp)', ci_rate: 'Bunga / Tahun (%)', ci_years: 'Periode (Tahun)', ci_freq: 'Frekuensi', ci_deposit: 'Setoran Rutin (Rp)',
    roi_initial: 'Investasi Awal (Rp)', roi_final: 'Nilai Akhir (Rp)', roi_years: 'Durasi (Tahun)',
    disc_orig: 'Harga Asli (Rp)', disc_pct: 'Diskon (%)',
    tax_before: 'Harga Sebelum Pajak (Rp)', tax_rate: 'Tarif PPN (%)',
    bmi_weight: 'Berat Badan (kg)', bmi_height: 'Tinggi Badan (cm)', bmi_age: 'Usia', bmi_gender: 'Jenis Kelamin',
    bmi_male: 'Laki-laki', bmi_female: 'Perempuan',
    zakat_title: 'Kalkulator Zakat', zakat_sub: 'Zakat Maal, Penghasilan & Fitrah',
    zakat_maal: 'Zakat Maal', zakat_income: 'Zakat Penghasilan', zakat_fitrah: 'Zakat Fitrah',
    zakat_maal_info: 'Nishab = 85 gram emas. Haul = 1 tahun. Tarif = 2,5%',
    zakat_income_info: 'Nishab = 653 kg beras. Tarif = 2,5% (bulanan)',
    zakat_fitrah_info: '2,7 kg beras per jiwa. Dibayar sebelum Idul Fitri.',
    zakat_gold_price: 'Harga Emas / gram (Rp)', zakat_total_wealth: 'Total Harta (Rp)',
    zakat_monthly_income: 'Penghasilan Bulanan (Rp)', zakat_rice_price: 'Harga Beras / kg (Rp)',
    zakat_num_people: 'Jumlah Jiwa', zakat_rice_price2: 'Harga Beras / kg (Rp)',
    btn_calc: 'Hitung', btn_calc_zakat: 'Hitung Zakat',
    prog_title: 'Kalkulator Programmer', prog_sub: 'Konversi basis bilangan & operasi bitwise',
    history_title: 'Riwayat', history_clear: 'Hapus Semua', history_empty: 'Belum ada riwayat',
    ce: 'CE', c: 'C',
    toast_copied: 'Disalin!', toast_mem_clear: 'Memori dihapus', toast_mem_saved: 'Disimpan ke memori', toast_history_clear: 'Riwayat dihapus',
    toast_light: '☀ Mode Terang', toast_dark: '🌙 Mode Gelap',
    topbar_standard: 'Kalkulator Standard', topbar_scientific: 'Kalkulator Scientific',
    topbar_programmer: 'Kalkulator Programmer', topbar_currency: 'Konversi Mata Uang',
    topbar_unit: 'Konversi Satuan', topbar_finance: 'Kalkulator Finansial', topbar_zakat: 'Kalkulator Zakat',
    freq_yearly: 'Tahunan', freq_semi: 'Semi-Tahunan', freq_quarterly: 'Kuartalan', freq_monthly: 'Bulanan', freq_daily: 'Harian',
    r_monthly_payment: 'Angsuran per Bulan', r_loan_amount: 'Total Pinjaman', r_total_payment: 'Total Pembayaran',
    r_total_interest: 'Total Bunga', r_interest_ratio: 'Rasio Bunga', r_amort_sample: 'Amortisasi (Sampel)',
    r_month: 'Bulan', r_interest: 'Bunga', r_principal: 'Modal Awal', r_remaining: 'Sisa Pokok',
    r_total_deposit: 'Total Setoran', r_final_value: 'Nilai Akhir Investasi', r_growth: 'Pertumbuhan',
    r_growth_per_year: 'Pertumbuhan per Tahun', r_year: 'Tahun', r_years: 'tahun',
    r_profit_loss: 'Keuntungan / Kerugian', r_roi_total: 'ROI Total', r_roi_annual: 'ROI per Tahun (CAGR)',
    r_multiplier: 'Faktor Pengganda', r_duration: 'Durasi',
    r_orig_price: 'Harga Asli', r_discount: 'Diskon', r_final_price: 'Harga Setelah Diskon', r_save: 'Hemat',
    r_price_before_tax: 'Harga Sebelum Pajak', r_price_after_tax: 'Harga Setelah Pajak', r_tax_rate: 'Tarif Pajak',
    r_category: 'Kategori', r_body_weight: 'Berat Badan', r_body_height: 'Tinggi Badan',
    r_ideal_weight: 'Berat Ideal (BMI 18.5-23)', r_bmr: 'BMR (Kalori Basal/hari)',
    r_active_medium: 'Kalori Aktif Sedang', r_active_high: 'Kalori Aktif Tinggi', r_day: 'hari',
    bmi_severe_thin: 'Sangat Kurus', bmi_very_thin: 'Kurus Berat', bmi_thin: 'Kurus',
    bmi_normal: 'Normal', bmi_overweight: 'Berat Lebih',
    bmi_obese1: 'Obesitas Kelas I', bmi_obese2: 'Obesitas Kelas II', bmi_obese3: 'Obesitas Kelas III',
  },
  en: {
    nav_tools: 'TOOLS', nav_convert: 'CONVERT', nav_finance: 'FINANCE',
    nav_standard: 'Standard', nav_scientific: 'Scientific', nav_programmer: 'Programmer',
    nav_currency: 'Currency', nav_unit: 'Unit Converter', nav_finance_calc: 'Financial', nav_zakat: 'Zakat Calculator',
    settings_lang: 'Language', settings_theme: 'Theme', settings_history: 'History',
    cur_title: 'Currency Converter', cur_amount: 'Amount', cur_from: 'From', cur_to: 'To',
    unit_title: 'Unit Converter', unit_sub: '10 complete conversion categories', unit_value: 'Value', unit_from: 'From', unit_to: 'To',
    fin_title: 'Financial Calculator', fin_sub: 'Investment, Loan, Tax & Health',
    fin_loan: 'Loan/Mortgage', fin_compound: 'Compound Interest', fin_discount: 'Discount',
    loan_amount: 'Loan Amount (Rp)', loan_rate: 'Annual Interest Rate (%)', loan_term: 'Term (Months)',
    ci_principal: 'Principal (Rp)', ci_rate: 'Annual Rate (%)', ci_years: 'Period (Years)', ci_freq: 'Frequency', ci_deposit: 'Regular Deposit (Rp)',
    roi_initial: 'Initial Investment (Rp)', roi_final: 'Final Value (Rp)', roi_years: 'Duration (Years)',
    disc_orig: 'Original Price (Rp)', disc_pct: 'Discount (%)',
    tax_before: 'Price Before Tax (Rp)', tax_rate: 'VAT Rate (%)',
    bmi_weight: 'Weight (kg)', bmi_height: 'Height (cm)', bmi_age: 'Age', bmi_gender: 'Gender',
    bmi_male: 'Male', bmi_female: 'Female',
    zakat_title: 'Zakat Calculator', zakat_sub: 'Zakat Maal, Income & Fitrah',
    zakat_maal: 'Zakat Maal', zakat_income: 'Income Zakat', zakat_fitrah: 'Zakat Fitrah',
    zakat_maal_info: 'Nisab = 85g gold. Haul = 1 year. Rate = 2.5%',
    zakat_income_info: 'Nisab = 653 kg rice. Rate = 2.5% monthly',
    zakat_fitrah_info: '2.7 kg rice per person. Paid before Eid al-Fitr.',
    zakat_gold_price: 'Gold Price / gram (Rp)', zakat_total_wealth: 'Total Wealth (Rp)',
    zakat_monthly_income: 'Monthly Income (Rp)', zakat_rice_price: 'Rice Price / kg (Rp)',
    zakat_num_people: 'Number of People', zakat_rice_price2: 'Rice Price / kg (Rp)',
    btn_calc: 'Calculate', btn_calc_zakat: 'Calculate Zakat',
    prog_title: 'Programmer Calculator', prog_sub: 'Number base conversion & bitwise operations',
    history_title: 'History', history_clear: 'Clear All', history_empty: 'No history yet',
    ce: 'CE', c: 'C',
    toast_copied: 'Copied!', toast_mem_clear: 'Memory cleared', toast_mem_saved: 'Saved to memory', toast_history_clear: 'History cleared',
    toast_light: 'Light Mode', toast_dark: 'Dark Mode',
    topbar_standard: 'Standard Calculator', topbar_scientific: 'Scientific Calculator',
    topbar_programmer: 'Programmer Calculator', topbar_currency: 'Currency Converter',
    topbar_unit: 'Unit Converter', topbar_finance: 'Financial Calculator', topbar_zakat: 'Zakat Calculator',
    freq_yearly: 'Annually', freq_semi: 'Semi-Annual', freq_quarterly: 'Quarterly', freq_monthly: 'Monthly', freq_daily: 'Daily',
    r_monthly_payment: 'Monthly Payment', r_loan_amount: 'Loan Amount', r_total_payment: 'Total Payment',
    r_total_interest: 'Total Interest', r_interest_ratio: 'Interest Ratio', r_amort_sample: 'Amortization (Sample)',
    r_month: 'Month', r_interest: 'Interest', r_principal: 'Principal', r_remaining: 'Balance',
    r_total_deposit: 'Total Deposits', r_final_value: 'Final Investment Value', r_growth: 'Growth',
    r_growth_per_year: 'Growth Per Year', r_year: 'Year', r_years: 'years',
    r_profit_loss: 'Profit / Loss', r_roi_total: 'Total ROI', r_roi_annual: 'Annual ROI (CAGR)',
    r_multiplier: 'Multiplier', r_duration: 'Duration',
    r_orig_price: 'Original Price', r_discount: 'Discount', r_final_price: 'Price After Discount', r_save: 'Savings',
    r_price_before_tax: 'Price Before Tax', r_price_after_tax: 'Price After Tax', r_tax_rate: 'Tax Rate',
    r_category: 'Category', r_body_weight: 'Body Weight', r_body_height: 'Height',
    r_ideal_weight: 'Ideal Weight (BMI 18.5-23)', r_bmr: 'BMR (Basal Calories/day)',
    r_active_medium: 'Moderate Activity Calories', r_active_high: 'High Activity Calories', r_day: 'day',
    bmi_severe_thin: 'Severely Underweight', bmi_very_thin: 'Very Underweight', bmi_thin: 'Underweight',
    bmi_normal: 'Normal', bmi_overweight: 'Overweight',
    bmi_obese1: 'Obesity Class I', bmi_obese2: 'Obesity Class II', bmi_obese3: 'Obesity Class III',
  },
  ar: {
    nav_tools: 'ادوات', nav_convert: 'تحويل', nav_finance: 'مالية',
    nav_standard: 'قياسي', nav_scientific: 'علمي', nav_programmer: 'مبرمج',
    nav_currency: 'العملات', nav_unit: 'وحدات القياس', nav_finance_calc: 'مالي', nav_zakat: 'حاسبة الزكاة',
    settings_lang: 'اللغة', settings_theme: 'المظهر', settings_history: 'السجل',
    cur_title: 'تحويل العملات', cur_amount: 'المبلغ', cur_from: 'من', cur_to: 'الى',
    unit_title: 'تحويل الوحدات', unit_sub: '10 فئات تحويل شاملة', unit_value: 'قيمة', unit_from: 'من', unit_to: 'الى',
    fin_title: 'الآلة الحاسبة المالية', fin_sub: 'استثمار قرض ضريبة وصحة',
    fin_loan: 'قرض', fin_compound: 'الفائدة المركبة', fin_discount: 'خصم',
    loan_amount: 'مبلغ القرض', loan_rate: 'معدل الفائدة (%)', loan_term: 'المدة (اشهر)',
    ci_principal: 'رأس المال', ci_rate: 'المعدل السنوي (%)', ci_years: 'المدة (سنوات)', ci_freq: 'التردد', ci_deposit: 'الوديعة الدورية',
    roi_initial: 'الاستثمار الاولي', roi_final: 'القيمة النهائية', roi_years: 'المدة (سنوات)',
    disc_orig: 'السعر الاصلي', disc_pct: 'الخصم (%)',
    tax_before: 'السعر قبل الضريبة', tax_rate: 'نسبة الضريبة (%)',
    bmi_weight: 'الوزن (كجم)', bmi_height: 'الطول (سم)', bmi_age: 'العمر', bmi_gender: 'الجنس',
    bmi_male: 'ذكر', bmi_female: 'انثى',
    zakat_title: 'حاسبة الزكاة', zakat_sub: 'زكاة المال والدخل والفطر',
    zakat_maal: 'زكاة المال', zakat_income: 'زكاة الدخل', zakat_fitrah: 'زكاة الفطر',
    zakat_maal_info: 'النصاب = 85 جرام ذهب. الحول = سنة. النسبة = 2.5%',
    zakat_income_info: 'النصاب = 653 كجم ارز. النسبة = 2.5%',
    zakat_fitrah_info: '2.7 كجم ارز للفرد. تدفع قبل عيد الفطر.',
    zakat_gold_price: 'سعر الذهب / جرام', zakat_total_wealth: 'اجمالي الثروة',
    zakat_monthly_income: 'الدخل الشهري', zakat_rice_price: 'سعر الارز / كجم',
    zakat_num_people: 'عدد الافراد', zakat_rice_price2: 'سعر الارز / كجم',
    btn_calc: 'احسب', btn_calc_zakat: 'احسب الزكاة',
    prog_title: 'حاسبة المبرمج', prog_sub: 'تحويل الانظمة العددية والعمليات البتية',
    history_title: 'السجل', history_clear: 'مسح الكل', history_empty: 'لا يوجد سجل',
    ce: 'مح', c: 'مسح',
    toast_copied: 'تم النسخ!', toast_mem_clear: 'تم مسح الذاكرة', toast_mem_saved: 'حفظ في الذاكرة', toast_history_clear: 'تم مسح السجل',
    toast_light: 'الوضع الفاتح', toast_dark: 'الوضع الداكن',
    topbar_standard: 'الآلة الحاسبة القياسية', topbar_scientific: 'الآلة العلمية',
    topbar_programmer: 'حاسبة المبرمج', topbar_currency: 'تحويل العملات',
    topbar_unit: 'تحويل الوحدات', topbar_finance: 'الآلة المالية', topbar_zakat: 'حاسبة الزكاة',
    freq_yearly: 'سنوي', freq_semi: 'نصف سنوي', freq_quarterly: 'ربع سنوي', freq_monthly: 'شهري', freq_daily: 'يومي',
    r_monthly_payment: 'القسط الشهري', r_loan_amount: 'مبلغ القرض', r_total_payment: 'اجمالي المدفوعات',
    r_total_interest: 'اجمالي الفائدة', r_interest_ratio: 'نسبة الفائدة', r_amort_sample: 'جدول الاطفاء (عينة)',
    r_month: 'شهر', r_interest: 'فائدة', r_principal: 'راس المال', r_remaining: 'الرصيد المتبقي',
    r_total_deposit: 'اجمالي الودائع', r_final_value: 'القيمة الاستثمارية النهائية', r_growth: 'النمو',
    r_growth_per_year: 'النمو السنوي', r_year: 'سنة', r_years: 'سنوات',
    r_profit_loss: 'ربح / خسارة', r_roi_total: 'اجمالي العائد', r_roi_annual: 'العائد السنوي (CAGR)',
    r_multiplier: 'معامل الضرب', r_duration: 'المدة',
    r_orig_price: 'السعر الاصلي', r_discount: 'خصم', r_final_price: 'السعر بعد الخصم', r_save: 'المدخرات',
    r_price_before_tax: 'السعر قبل الضريبة', r_price_after_tax: 'السعر بعد الضريبة', r_tax_rate: 'معدل الضريبة',
    r_category: 'الفئة', r_body_weight: 'وزن الجسم', r_body_height: 'الطول',
    r_ideal_weight: 'الوزن المثالي (BMI 18.5-23)', r_bmr: 'معدل الايض الاساسي',
    r_active_medium: 'سعرات النشاط المتوسط', r_active_high: 'سعرات النشاط العالي', r_day: 'يوم',
    bmi_severe_thin: 'نحافة شديدة جدا', bmi_very_thin: 'نحافة شديدة', bmi_thin: 'نحيف',
    bmi_normal: 'طبيعي', bmi_overweight: 'زيادة الوزن',
    bmi_obese1: 'سمنة الدرجة الاولى', bmi_obese2: 'سمنة الدرجة الثانية', bmi_obese3: 'سمنة الدرجة الثالثة',
  },
  ja: {
    nav_tools: 'ツール', nav_convert: '変換', nav_finance: 'ファイナンス',
    nav_standard: '標準', nav_scientific: '科学', nav_programmer: 'プログラマー',
    nav_currency: '通貨', nav_unit: '単位変換', nav_finance_calc: '財務', nav_zakat: 'ザカット計算',
    settings_lang: '言語', settings_theme: 'テーマ', settings_history: '履歴',
    cur_title: '通貨換算', cur_amount: '金額', cur_from: 'から', cur_to: 'へ',
    unit_title: '単位変換', unit_sub: '10カテゴリーの変換', unit_value: '値', unit_from: 'から', unit_to: 'へ',
    fin_title: '財務計算機', fin_sub: '投資、ローン、税金',
    fin_loan: 'ローン', fin_compound: '複利', fin_discount: '割引',
    loan_amount: 'ローン金額', loan_rate: '年利率 (%)', loan_term: '期間（月）',
    ci_principal: '元本', ci_rate: '年利率 (%)', ci_years: '期間（年）', ci_freq: '頻度', ci_deposit: '定期預金',
    roi_initial: '初期投資', roi_final: '最終価値', roi_years: '期間（年）',
    disc_orig: '定価', disc_pct: '割引率 (%)',
    tax_before: '税抜価格', tax_rate: '消費税率 (%)',
    bmi_weight: '体重 (kg)', bmi_height: '身長 (cm)', bmi_age: '年齢', bmi_gender: '性別',
    bmi_male: '男性', bmi_female: '女性',
    zakat_title: 'ザカット計算機', zakat_sub: 'ザカット計算',
    zakat_maal: 'ザカット・マール', zakat_income: '所得ザカット', zakat_fitrah: 'ザカット・フィトラ',
    zakat_maal_info: 'ニサブ = 金85g、1年、2.5%',
    zakat_income_info: 'ニサブ = 653kg米。税率2.5%',
    zakat_fitrah_info: '米2.7kg/人。イード前に支払う。',
    zakat_gold_price: '金価格/g', zakat_total_wealth: '総資産',
    zakat_monthly_income: '月収', zakat_rice_price: '米価格/kg',
    zakat_num_people: '人数', zakat_rice_price2: '米価格/kg',
    btn_calc: '計算', btn_calc_zakat: 'ザカット計算',
    prog_title: 'プログラマー電卓', prog_sub: '進数変換とビット演算',
    history_title: '履歴', history_clear: '全削除', history_empty: '履歴なし',
    ce: 'CE', c: 'C',
    toast_copied: 'コピー!', toast_mem_clear: 'メモリクリア', toast_mem_saved: 'メモリ保存', toast_history_clear: '履歴削除',
    toast_light: 'ライトモード', toast_dark: 'ダークモード',
    topbar_standard: '標準計算機', topbar_scientific: '科学計算機',
    topbar_programmer: 'プログラマー電卓', topbar_currency: '通貨換算',
    topbar_unit: '単位変換', topbar_finance: '財務計算機', topbar_zakat: 'ザカット計算機',
    freq_yearly: '毎年', freq_semi: '半年ごと', freq_quarterly: '四半期ごと', freq_monthly: '毎月', freq_daily: '毎日',
    r_monthly_payment: '月々の支払い', r_loan_amount: '借入金額', r_total_payment: '総支払額',
    r_total_interest: '総利息', r_interest_ratio: '利息比率', r_amort_sample: '償却スケジュール',
    r_month: '月', r_interest: '利息', r_principal: '元本', r_remaining: '残高',
    r_total_deposit: '総預入額', r_final_value: '最終投資額', r_growth: '成長率',
    r_growth_per_year: '年間成長', r_year: '年', r_years: '年',
    r_profit_loss: '利益/損失', r_roi_total: '総ROI', r_roi_annual: '年間ROI (CAGR)',
    r_multiplier: '倍率', r_duration: '期間',
    r_orig_price: '元の価格', r_discount: '割引', r_final_price: '割引後の価格', r_save: '節約額',
    r_price_before_tax: '税抜価格', r_price_after_tax: '税込価格', r_tax_rate: '税率',
    r_category: 'カテゴリー', r_body_weight: '体重', r_body_height: '身長',
    r_ideal_weight: '理想体重 (BMI 18.5-23)', r_bmr: '基礎代謝量',
    r_active_medium: '中程度の活動カロリー', r_active_high: '高活動カロリー', r_day: '日',
    bmi_severe_thin: '重度の痩せ', bmi_very_thin: '非常に痩せ', bmi_thin: '痩せ',
    bmi_normal: '普通', bmi_overweight: '過体重',
    bmi_obese1: '肥満1度', bmi_obese2: '肥満2度', bmi_obese3: '肥満3度',
  },
  ko: {
    nav_tools: '도구', nav_convert: '변환', nav_finance: '금융',
    nav_standard: '표준', nav_scientific: '과학', nav_programmer: '프로그래머',
    nav_currency: '통화', nav_unit: '단위 변환', nav_finance_calc: '금융', nav_zakat: '자캇 계산기',
    settings_lang: '언어', settings_theme: '테마', settings_history: '기록',
    cur_title: '환율 변환', cur_amount: '금액', cur_from: '에서', cur_to: '으로',
    unit_title: '단위 변환', unit_sub: '10가지 변환 카테고리', unit_value: '값', unit_from: '에서', unit_to: '으로',
    fin_title: '금융 계산기', fin_sub: '투자, 대출, 세금 & 건강',
    fin_loan: '대출', fin_compound: '복리', fin_discount: '할인',
    loan_amount: '대출 금액', loan_rate: '연 이자율 (%)', loan_term: '기간 (개월)',
    ci_principal: '원금', ci_rate: '연 이자율 (%)', ci_years: '기간 (년)', ci_freq: '빈도', ci_deposit: '정기 예금',
    roi_initial: '초기 투자', roi_final: '최종 가치', roi_years: '기간 (년)',
    disc_orig: '정가', disc_pct: '할인율 (%)',
    tax_before: '세전 가격', tax_rate: '부가세율 (%)',
    bmi_weight: '체중 (kg)', bmi_height: '키 (cm)', bmi_age: '나이', bmi_gender: '성별',
    bmi_male: '남성', bmi_female: '여성',
    zakat_title: '자캇 계산기', zakat_sub: '자캇 말, 소득 및 피트라',
    zakat_maal: '자캇 말', zakat_income: '소득 자캇', zakat_fitrah: '자캇 피트라',
    zakat_maal_info: '니샤브 = 금 85g. 하울 = 1년. 세율 = 2.5%',
    zakat_income_info: '니샤브 = 쌀 653kg. 세율 = 2.5%',
    zakat_fitrah_info: '쌀 2.7kg/인. 이드 전 납부.',
    zakat_gold_price: '금 가격/g', zakat_total_wealth: '총 자산',
    zakat_monthly_income: '월 소득', zakat_rice_price: '쌀 가격/kg',
    zakat_num_people: '인원 수', zakat_rice_price2: '쌀 가격/kg',
    btn_calc: '계산', btn_calc_zakat: '자캇 계산',
    prog_title: '프로그래머 계산기', prog_sub: '진법 변환 및 비트 연산',
    history_title: '기록', history_clear: '전체 삭제', history_empty: '기록 없음',
    ce: 'CE', c: 'C',
    toast_copied: '복사됨!', toast_mem_clear: '메모리 삭제', toast_mem_saved: '메모리 저장', toast_history_clear: '기록 삭제',
    toast_light: '라이트 모드', toast_dark: '다크 모드',
    topbar_standard: '표준 계산기', topbar_scientific: '과학 계산기',
    topbar_programmer: '프로그래머 계산기', topbar_currency: '환율 변환',
    topbar_unit: '단위 변환', topbar_finance: '금융 계산기', topbar_zakat: '자캇 계산기',
    freq_yearly: '연간', freq_semi: '반기', freq_quarterly: '분기별', freq_monthly: '월간', freq_daily: '일별',
    r_monthly_payment: '월 납부액', r_loan_amount: '대출 금액', r_total_payment: '총 납부액',
    r_total_interest: '총 이자', r_interest_ratio: '이자 비율', r_amort_sample: '상환 일정 (샘플)',
    r_month: '월', r_interest: '이자', r_principal: '원금', r_remaining: '잔액',
    r_total_deposit: '총 예금', r_final_value: '최종 투자 가치', r_growth: '성장률',
    r_growth_per_year: '연간 성장', r_year: '년', r_years: '년',
    r_profit_loss: '수익/손실', r_roi_total: '총 ROI', r_roi_annual: '연간 ROI (CAGR)',
    r_multiplier: '배율', r_duration: '기간',
    r_orig_price: '원래 가격', r_discount: '할인', r_final_price: '할인 후 가격', r_save: '절약액',
    r_price_before_tax: '세전 가격', r_price_after_tax: '세후 가격', r_tax_rate: '세율',
    r_category: '카테고리', r_body_weight: '체중', r_body_height: '키',
    r_ideal_weight: '이상 체중 (BMI 18.5-23)', r_bmr: '기초 대사량',
    r_active_medium: '보통 활동 칼로리', r_active_high: '높은 활동 칼로리', r_day: '일',
    bmi_severe_thin: '심각한 저체중', bmi_very_thin: '매우 저체중', bmi_thin: '저체중',
    bmi_normal: '정상', bmi_overweight: '과체중',
    bmi_obese1: '비만 1단계', bmi_obese2: '비만 2단계', bmi_obese3: '비만 3단계',
  },
  zh: {
    nav_tools: '工具', nav_convert: '转换', nav_finance: '金融',
    nav_standard: '标准', nav_scientific: '科学', nav_programmer: '程序员',
    nav_currency: '货币', nav_unit: '单位转换', nav_finance_calc: '金融', nav_zakat: '天课计算器',
    settings_lang: '语言', settings_theme: '主题', settings_history: '历史',
    cur_title: '货币转换', cur_amount: '金额', cur_from: '从', cur_to: '到',
    unit_title: '单位转换', unit_sub: '10个完整的转换类别', unit_value: '值', unit_from: '从', unit_to: '到',
    fin_title: '财务计算器', fin_sub: '投资、贷款、税务',
    fin_loan: '贷款', fin_compound: '复利', fin_discount: '折扣',
    loan_amount: '贷款金额', loan_rate: '年利率 (%)', loan_term: '期限（月）',
    ci_principal: '本金', ci_rate: '年利率 (%)', ci_years: '期限（年）', ci_freq: '频率', ci_deposit: '定期存款',
    roi_initial: '初始投资', roi_final: '最终价值', roi_years: '期限（年）',
    disc_orig: '原价', disc_pct: '折扣 (%)',
    tax_before: '税前价格', tax_rate: '增值税率 (%)',
    bmi_weight: '体重 (kg)', bmi_height: '身高 (cm)', bmi_age: '年龄', bmi_gender: '性别',
    bmi_male: '男性', bmi_female: '女性',
    zakat_title: '天课计算器', zakat_sub: '天课计算',
    zakat_maal: '财产天课', zakat_income: '收入天课', zakat_fitrah: '开斋天课',
    zakat_maal_info: '尼萨布 = 黄金85g。周年 = 1年。税率 = 2.5%',
    zakat_income_info: '尼萨布 = 大米653kg。税率 = 2.5%',
    zakat_fitrah_info: '每人2.7kg大米。斋节前缴纳。',
    zakat_gold_price: '黄金价格/克', zakat_total_wealth: '总资产',
    zakat_monthly_income: '月收入', zakat_rice_price: '大米价格/kg',
    zakat_num_people: '人数', zakat_rice_price2: '大米价格/kg',
    btn_calc: '计算', btn_calc_zakat: '计算天课',
    prog_title: '程序员计算器', prog_sub: '数制转换和位运算',
    history_title: '历史', history_clear: '全部清除', history_empty: '暂无历史记录',
    ce: 'CE', c: 'C',
    toast_copied: '已复制!', toast_mem_clear: '内存已清除', toast_mem_saved: '已保存到内存', toast_history_clear: '历史已清除',
    toast_light: '浅色模式', toast_dark: '深色模式',
    topbar_standard: '标准计算器', topbar_scientific: '科学计算器',
    topbar_programmer: '程序员计算器', topbar_currency: '货币转换',
    topbar_unit: '单位转换', topbar_finance: '财务计算器', topbar_zakat: '天课计算器',
    freq_yearly: '每年', freq_semi: '半年', freq_quarterly: '每季度', freq_monthly: '每月', freq_daily: '每天',
    r_monthly_payment: '月供', r_loan_amount: '贷款金额', r_total_payment: '总还款',
    r_total_interest: '总利息', r_interest_ratio: '利息比率', r_amort_sample: '还款计划（样本）',
    r_month: '月', r_interest: '利息', r_principal: '本金', r_remaining: '剩余余额',
    r_total_deposit: '总存款', r_final_value: '最终投资价值', r_growth: '增长率',
    r_growth_per_year: '年增长', r_year: '年', r_years: '年',
    r_profit_loss: '盈亏', r_roi_total: '总ROI', r_roi_annual: '年化ROI (CAGR)',
    r_multiplier: '倍数', r_duration: '期限',
    r_orig_price: '原价', r_discount: '折扣', r_final_price: '折后价', r_save: '节省',
    r_price_before_tax: '税前价格', r_price_after_tax: '税后价格', r_tax_rate: '税率',
    r_category: '类别', r_body_weight: '体重', r_body_height: '身高',
    r_ideal_weight: '理想体重 (BMI 18.5-23)', r_bmr: '基础代谢率',
    r_active_medium: '中等活动卡路里', r_active_high: '高活动卡路里', r_day: '天',
    bmi_severe_thin: '严重消瘦', bmi_very_thin: '重度消瘦', bmi_thin: '消瘦',
    bmi_normal: '正常', bmi_overweight: '超重',
    bmi_obese1: '肥胖一级', bmi_obese2: '肥胖二级', bmi_obese3: '肥胖三级',
  },
  es: {
    nav_tools: 'HERRAMIENTAS', nav_convert: 'CONVERTIR', nav_finance: 'FINANZAS',
    nav_standard: 'Estandar', nav_scientific: 'Cientifica', nav_programmer: 'Programador',
    nav_currency: 'Moneda', nav_unit: 'Conversion', nav_finance_calc: 'Financiero', nav_zakat: 'Calculadora Zakat',
    settings_lang: 'Idioma', settings_theme: 'Tema', settings_history: 'Historial',
    cur_title: 'Conversor de Moneda', cur_amount: 'Cantidad', cur_from: 'De', cur_to: 'A',
    unit_title: 'Conversor de Unidades', unit_sub: '10 categorias completas', unit_value: 'Valor', unit_from: 'De', unit_to: 'A',
    fin_title: 'Calculadora Financiera', fin_sub: 'Inversion, Prestamo, Impuesto',
    fin_loan: 'Prestamo', fin_compound: 'Interes Compuesto', fin_discount: 'Descuento',
    loan_amount: 'Monto del Prestamo', loan_rate: 'Tasa Anual (%)', loan_term: 'Plazo (Meses)',
    ci_principal: 'Capital Inicial', ci_rate: 'Tasa Anual (%)', ci_years: 'Periodo (Anos)', ci_freq: 'Frecuencia', ci_deposit: 'Deposito Periodico',
    roi_initial: 'Inversion Inicial', roi_final: 'Valor Final', roi_years: 'Duracion (Anos)',
    disc_orig: 'Precio Original', disc_pct: 'Descuento (%)',
    tax_before: 'Precio sin IVA', tax_rate: 'Tasa IVA (%)',
    bmi_weight: 'Peso (kg)', bmi_height: 'Altura (cm)', bmi_age: 'Edad', bmi_gender: 'Genero',
    bmi_male: 'Masculino', bmi_female: 'Femenino',
    zakat_title: 'Calculadora Zakat', zakat_sub: 'Zakat Maal, Ingresos y Fitrah',
    zakat_maal: 'Zakat Maal', zakat_income: 'Zakat de Ingresos', zakat_fitrah: 'Zakat Fitrah',
    zakat_maal_info: 'Nisab = 85g oro. Haul = 1 ano. Tasa = 2.5%',
    zakat_income_info: 'Nisab = 653 kg arroz. Tasa = 2.5%',
    zakat_fitrah_info: '2.7 kg de arroz por persona. Pagar antes del Eid.',
    zakat_gold_price: 'Precio del oro/g', zakat_total_wealth: 'Patrimonio Total',
    zakat_monthly_income: 'Ingreso Mensual', zakat_rice_price: 'Precio arroz/kg',
    zakat_num_people: 'Numero de Personas', zakat_rice_price2: 'Precio arroz/kg',
    btn_calc: 'Calcular', btn_calc_zakat: 'Calcular Zakat',
    prog_title: 'Calculadora de Programador', prog_sub: 'Conversion de bases y operaciones bitwise',
    history_title: 'Historial', history_clear: 'Borrar Todo', history_empty: 'Sin historial',
    ce: 'CE', c: 'C',
    toast_copied: 'Copiado!', toast_mem_clear: 'Memoria borrada', toast_mem_saved: 'Guardado en memoria', toast_history_clear: 'Historial borrado',
    toast_light: 'Modo Claro', toast_dark: 'Modo Oscuro',
    topbar_standard: 'Calculadora Estandar', topbar_scientific: 'Calculadora Cientifica',
    topbar_programmer: 'Calculadora de Programador', topbar_currency: 'Conversor de Moneda',
    topbar_unit: 'Conversor de Unidades', topbar_finance: 'Calculadora Financiera', topbar_zakat: 'Calculadora Zakat',
    freq_yearly: 'Anual', freq_semi: 'Semestral', freq_quarterly: 'Trimestral', freq_monthly: 'Mensual', freq_daily: 'Diario',
    r_monthly_payment: 'Cuota Mensual', r_loan_amount: 'Monto del Prestamo', r_total_payment: 'Pago Total',
    r_total_interest: 'Interes Total', r_interest_ratio: 'Ratio de Interes', r_amort_sample: 'Amortizacion (Muestra)',
    r_month: 'Mes', r_interest: 'Interes', r_principal: 'Capital', r_remaining: 'Saldo Restante',
    r_total_deposit: 'Depositos Totales', r_final_value: 'Valor Final de Inversion', r_growth: 'Crecimiento',
    r_growth_per_year: 'Crecimiento Anual', r_year: 'Ano', r_years: 'anos',
    r_profit_loss: 'Ganancia / Perdida', r_roi_total: 'ROI Total', r_roi_annual: 'ROI Anual (CAGR)',
    r_multiplier: 'Factor Multiplicador', r_duration: 'Duracion',
    r_orig_price: 'Precio Original', r_discount: 'Descuento', r_final_price: 'Precio con Descuento', r_save: 'Ahorro',
    r_price_before_tax: 'Precio sin Impuesto', r_price_after_tax: 'Precio con Impuesto', r_tax_rate: 'Tasa Impositiva',
    r_category: 'Categoria', r_body_weight: 'Peso Corporal', r_body_height: 'Altura',
    r_ideal_weight: 'Peso Ideal (IMC 18.5-23)', r_bmr: 'TMB (Calorias Basales/dia)',
    r_active_medium: 'Calorias Actividad Moderada', r_active_high: 'Calorias Actividad Alta', r_day: 'dia',
    bmi_severe_thin: 'Desnutricion Severa', bmi_very_thin: 'Muy Bajo Peso', bmi_thin: 'Bajo Peso',
    bmi_normal: 'Normal', bmi_overweight: 'Sobrepeso',
    bmi_obese1: 'Obesidad Grado I', bmi_obese2: 'Obesidad Grado II', bmi_obese3: 'Obesidad Grado III',
  },
  fr: {
    nav_tools: 'OUTILS', nav_convert: 'CONVERTIR', nav_finance: 'FINANCE',
    nav_standard: 'Standard', nav_scientific: 'Scientifique', nav_programmer: 'Programmeur',
    nav_currency: 'Devise', nav_unit: 'Conversion', nav_finance_calc: 'Financier', nav_zakat: 'Calcul Zakat',
    settings_lang: 'Langue', settings_theme: 'Theme', settings_history: 'Historique',
    cur_title: 'Convertisseur de Devises', cur_amount: 'Montant', cur_from: 'De', cur_to: 'A',
    unit_title: "Convertisseur d'Unites", unit_sub: '10 categories de conversion', unit_value: 'Valeur', unit_from: 'De', unit_to: 'A',
    fin_title: 'Calculatrice Financiere', fin_sub: 'Investissement, Pret, Taxe',
    fin_loan: 'Pret', fin_compound: 'Interet Compose', fin_discount: 'Remise',
    loan_amount: 'Montant du Pret', loan_rate: 'Taux Annuel (%)', loan_term: 'Duree (Mois)',
    ci_principal: 'Capital Initial', ci_rate: 'Taux Annuel (%)', ci_years: 'Periode (Ans)', ci_freq: 'Frequence', ci_deposit: 'Depot Periodique',
    roi_initial: 'Investissement Initial', roi_final: 'Valeur Finale', roi_years: 'Duree (Ans)',
    disc_orig: 'Prix Original', disc_pct: 'Remise (%)',
    tax_before: 'Prix HT', tax_rate: 'Taux TVA (%)',
    bmi_weight: 'Poids (kg)', bmi_height: 'Taille (cm)', bmi_age: 'Age', bmi_gender: 'Genre',
    bmi_male: 'Masculin', bmi_female: 'Feminin',
    zakat_title: 'Calculateur de Zakat', zakat_sub: 'Zakat Maal, Revenu et Fitrah',
    zakat_maal: 'Zakat Maal', zakat_income: 'Zakat sur le Revenu', zakat_fitrah: 'Zakat Fitrah',
    zakat_maal_info: 'Nissab = 85g or. Hawl = 1 an. Taux = 2.5%',
    zakat_income_info: 'Nissab = 653 kg riz. Taux = 2.5%',
    zakat_fitrah_info: "2.7 kg de riz par personne. A payer avant l'Aid.",
    zakat_gold_price: "Prix de l'or/g", zakat_total_wealth: 'Patrimoine Total',
    zakat_monthly_income: 'Revenu Mensuel', zakat_rice_price: 'Prix du riz/kg',
    zakat_num_people: 'Nombre de personnes', zakat_rice_price2: 'Prix du riz/kg',
    btn_calc: 'Calculer', btn_calc_zakat: 'Calculer Zakat',
    prog_title: 'Calculatrice Programmeur', prog_sub: 'Conversion de base et operations bit',
    history_title: 'Historique', history_clear: 'Tout effacer', history_empty: "Pas d'historique",
    ce: 'CE', c: 'C',
    toast_copied: 'Copie!', toast_mem_clear: 'Memoire effacee', toast_mem_saved: 'Enregistre en memoire', toast_history_clear: 'Historique efface',
    toast_light: 'Mode Clair', toast_dark: 'Mode Sombre',
    topbar_standard: 'Calculatrice Standard', topbar_scientific: 'Calculatrice Scientifique',
    topbar_programmer: 'Calculatrice Programmeur', topbar_currency: 'Convertisseur de Devises',
    topbar_unit: "Convertisseur d'Unites", topbar_finance: 'Calculatrice Financiere', topbar_zakat: 'Calculateur de Zakat',
    freq_yearly: 'Annuel', freq_semi: 'Semestriel', freq_quarterly: 'Trimestriel', freq_monthly: 'Mensuel', freq_daily: 'Quotidien',
    r_monthly_payment: 'Mensualite', r_loan_amount: 'Montant du Pret', r_total_payment: 'Total des Paiements',
    r_total_interest: 'Total des Interets', r_interest_ratio: "Ratio d'Interet", r_amort_sample: 'Amortissement (Echantillon)',
    r_month: 'Mois', r_interest: 'Interet', r_principal: 'Capital', r_remaining: 'Solde Restant',
    r_total_deposit: 'Total des Depots', r_final_value: 'Valeur Finale', r_growth: 'Croissance',
    r_growth_per_year: 'Croissance Annuelle', r_year: 'Annee', r_years: 'ans',
    r_profit_loss: 'Profit / Perte', r_roi_total: 'ROI Total', r_roi_annual: 'ROI Annuel (CAGR)',
    r_multiplier: 'Multiplicateur', r_duration: 'Duree',
    r_orig_price: 'Prix Original', r_discount: 'Remise', r_final_price: 'Prix Apres Remise', r_save: 'Economies',
    r_price_before_tax: 'Prix HT', r_price_after_tax: 'Prix TTC', r_tax_rate: 'Taux de Taxe',
    r_category: 'Categorie', r_body_weight: 'Poids Corporel', r_body_height: 'Taille',
    r_ideal_weight: 'Poids Ideal (IMC 18.5-23)', r_bmr: 'MB (Calories de base/jour)',
    r_active_medium: 'Calories Activite Moderee', r_active_high: 'Calories Activite Intense', r_day: 'jour',
    bmi_severe_thin: 'Maigreur Severe', bmi_very_thin: 'Tres Maigre', bmi_thin: 'Maigre',
    bmi_normal: 'Normal', bmi_overweight: 'Surpoids',
    bmi_obese1: 'Obesite Classe I', bmi_obese2: 'Obesite Classe II', bmi_obese3: 'Obesite Classe III',
  },
  de: {
    nav_tools: 'WERKZEUGE', nav_convert: 'UMRECHNEN', nav_finance: 'FINANZEN',
    nav_standard: 'Standard', nav_scientific: 'Wissenschaftlich', nav_programmer: 'Programmierer',
    nav_currency: 'Wahrung', nav_unit: 'Einheiten', nav_finance_calc: 'Finanziell', nav_zakat: 'Zakat-Rechner',
    settings_lang: 'Sprache', settings_theme: 'Thema', settings_history: 'Verlauf',
    cur_title: 'Wahrungsumrechner', cur_amount: 'Betrag', cur_from: 'Von', cur_to: 'Nach',
    unit_title: 'Einheitenumrechner', unit_sub: '10 vollstandige Kategorien', unit_value: 'Wert', unit_from: 'Von', unit_to: 'Nach',
    fin_title: 'Finanzrechner', fin_sub: 'Investition, Kredit, Steuer',
    fin_loan: 'Kredit', fin_compound: 'Zinseszins', fin_discount: 'Rabatt',
    loan_amount: 'Kreditbetrag', loan_rate: 'Jahreszinssatz (%)', loan_term: 'Laufzeit (Monate)',
    ci_principal: 'Hauptbetrag', ci_rate: 'Jahreszins (%)', ci_years: 'Laufzeit (Jahre)', ci_freq: 'Haufigkeit', ci_deposit: 'Regelmasige Einzahlung',
    roi_initial: 'Anfangsinvestition', roi_final: 'Endwert', roi_years: 'Dauer (Jahre)',
    disc_orig: 'Originalpreis', disc_pct: 'Rabatt (%)',
    tax_before: 'Preis ohne MwSt.', tax_rate: 'MwSt-Satz (%)',
    bmi_weight: 'Gewicht (kg)', bmi_height: 'Grose (cm)', bmi_age: 'Alter', bmi_gender: 'Geschlecht',
    bmi_male: 'Mannlich', bmi_female: 'Weiblich',
    zakat_title: 'Zakat-Rechner', zakat_sub: 'Zakat Berechnung',
    zakat_maal: 'Zakat Maal', zakat_income: 'Einkommenszakat', zakat_fitrah: 'Zakat Fitrah',
    zakat_maal_info: 'Nisab = 85g Gold. Haul = 1 Jahr. Satz = 2.5%',
    zakat_income_info: 'Nisab = 653 kg Reis. Satz = 2.5%',
    zakat_fitrah_info: '2,7 kg Reis pro Person. Vor Eid zu zahlen.',
    zakat_gold_price: 'Goldpreis/g', zakat_total_wealth: 'Gesamtvermogen',
    zakat_monthly_income: 'Monatseinkommen', zakat_rice_price: 'Reispreis/kg',
    zakat_num_people: 'Personenzahl', zakat_rice_price2: 'Reispreis/kg',
    btn_calc: 'Berechnen', btn_calc_zakat: 'Zakat berechnen',
    prog_title: 'Programmierrechner', prog_sub: 'Zahlensysteme & Bitoperationen',
    history_title: 'Verlauf', history_clear: 'Alles loschen', history_empty: 'Kein Verlauf',
    ce: 'CE', c: 'C',
    toast_copied: 'Kopiert!', toast_mem_clear: 'Speicher geloscht', toast_mem_saved: 'Im Speicher gespeichert', toast_history_clear: 'Verlauf geloscht',
    toast_light: 'Hellmodus', toast_dark: 'Dunkelmodus',
    topbar_standard: 'Standardrechner', topbar_scientific: 'Wissenschaftlicher Rechner',
    topbar_programmer: 'Programmierrechner', topbar_currency: 'Wahrungsumrechner',
    topbar_unit: 'Einheitenumrechner', topbar_finance: 'Finanzrechner', topbar_zakat: 'Zakat-Rechner',
    freq_yearly: 'Jahrlich', freq_semi: 'Halbjahrlich', freq_quarterly: 'Vierteljahrlich', freq_monthly: 'Monatlich', freq_daily: 'Taglich',
    r_monthly_payment: 'Monatliche Rate', r_loan_amount: 'Kreditbetrag', r_total_payment: 'Gesamtzahlung',
    r_total_interest: 'Gesamtzinsen', r_interest_ratio: 'Zinsverhaltniss', r_amort_sample: 'Tilgungsplan (Auszug)',
    r_month: 'Monat', r_interest: 'Zinsen', r_principal: 'Hauptbetrag', r_remaining: 'Restschuld',
    r_total_deposit: 'Gesamteinlagen', r_final_value: 'Endwert der Investition', r_growth: 'Wachstum',
    r_growth_per_year: 'Jahrliches Wachstum', r_year: 'Jahr', r_years: 'Jahre',
    r_profit_loss: 'Gewinn / Verlust', r_roi_total: 'Gesamt-ROI', r_roi_annual: 'Jahrlicher ROI (CAGR)',
    r_multiplier: 'Multiplikator', r_duration: 'Dauer',
    r_orig_price: 'Originalpreis', r_discount: 'Rabatt', r_final_price: 'Preis nach Rabatt', r_save: 'Ersparnis',
    r_price_before_tax: 'Preis ohne MwSt.', r_price_after_tax: 'Preis mit MwSt.', r_tax_rate: 'Steuersatz',
    r_category: 'Kategorie', r_body_weight: 'Korpergewicht', r_body_height: 'Korpergrosse',
    r_ideal_weight: 'Idealgewicht (BMI 18.5-23)', r_bmr: 'Grundumsatz (Kalorien/Tag)',
    r_active_medium: 'Kalorien moderate Aktivitat', r_active_high: 'Kalorien hohe Aktivitat', r_day: 'Tag',
    bmi_severe_thin: 'Stark Untergewichtig', bmi_very_thin: 'Sehr Untergewichtig', bmi_thin: 'Untergewichtig',
    bmi_normal: 'Normal', bmi_overweight: 'Ubergewichtig',
    bmi_obese1: 'Adipositas Grad I', bmi_obese2: 'Adipositas Grad II', bmi_obese3: 'Adipositas Grad III',
  }
};

const RTL_LANGS = ['ar'];
let currentLang = 'id';

function t(key) {
  return (I18N[currentLang] && I18N[currentLang][key])
      || (I18N['en'] && I18N['en'][key])
      || key;
}

function setLanguage(lang) {
  currentLang = lang;
  const isRTL = RTL_LANGS.includes(lang);
  document.documentElement.setAttribute('dir', isRTL ? 'rtl' : 'ltr');
  document.documentElement.setAttribute('lang', lang);
  applyTranslations();
}

function applyTranslations() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    el.textContent = t(el.getAttribute('data-i18n'));
  });

  const ciFreq = document.getElementById('ci-freq');
  if (ciFreq) {
    const cur = ciFreq.value;
    const opts = [
      { v: '1', k: 'freq_yearly' }, { v: '2', k: 'freq_semi' },
      { v: '4', k: 'freq_quarterly' }, { v: '12', k: 'freq_monthly' }, { v: '365', k: 'freq_daily' }
    ];
    ciFreq.innerHTML = opts.map(o => `<option value="${o.v}"${o.v === cur ? ' selected' : ''}>${t(o.k)}</option>`).join('');
  }

  const bmiGender = document.getElementById('bmi-gender');
  if (bmiGender) {
    const cur = bmiGender.value;
    bmiGender.innerHTML = `<option value="male"${cur === 'male' ? ' selected' : ''}>${t('bmi_male')}</option><option value="female"${cur === 'female' ? ' selected' : ''}>${t('bmi_female')}</option>`;
  }

  const topbarTitle = document.getElementById('topbarTitle');
  if (topbarTitle) {
    const activeNav = document.querySelector('.nav-item.active');
    if (activeNav) {
      const tabName = activeNav.getAttribute('data-tab');
      const translated = t('topbar_' + tabName);
      if (translated !== 'topbar_' + tabName) topbarTitle.textContent = translated;
    }
  }

  const stdCe = document.querySelector('[data-i18n-btn="ce"]');
  const stdC = document.querySelector('[data-i18n-btn="c"]');
  if (stdCe) stdCe.textContent = t('ce');
  if (stdC) stdC.textContent = t('c');

  const histTitle = document.querySelector('#historyPanel .history-panel-head h3');
  if (histTitle) histTitle.textContent = t('history_title');
  const histClear = document.querySelector('#historyPanel .history-clear-btn');
  if (histClear) histClear.textContent = t('history_clear');

  if (typeof renderHistoryList === 'function') {
    const panel = document.getElementById('historyPanel');
    if (panel && panel.classList.contains('open')) renderHistoryList();
    else {
      const emptyEl = document.querySelector('#historyList .history-empty');
      if (emptyEl) emptyEl.textContent = t('history_empty');
    }
  }
}

window.addEventListener('DOMContentLoaded', () => {
  applyTranslations();
});
